### ISSUE TITLE
Remove use of rgdal

### ISSUE THREAD

**Issue by rsbivand** [serafinialessio/mapping#3]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by rsbivand** [comment]
Please take action as soon as possible to remove any retiring packages. See also https://r-spatial.org/r/2023/05/15/evolution4.html.

**Comment by rsbivand** [comment]
@serafinialessio See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by serafinialessio** [comment]
@rsbivand I removed the dependencies but I already have this note and I cannot submit the package:

The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)

This is because of the import of tmap and mapview package in description. How can I solve that and submit again the package?

**Comment by rsbivand** [comment]
Please attach the complete CRAN submission check log if you have already submitted. If any package you import, itself imports `sp`, you should see these startup messages, but `sp` does not import the retiring packages, it suggests them. Which version of `sp` are you running locally?

**Comment by serafinialessio** [comment]
@rsbivand this is the message from cran pre-test:

* using log directory 'd:/RCompile/CRANincoming/R-devel/mapping.Rcheck'
* using R Under development (unstable) (2023-08-19 r84989 ucrt)
* using platform: x86_64-w64-mingw32
* R was compiled by
    gcc.exe (GCC) 12.2.0
    GNU Fortran (GCC) 12.2.0
* running under: Windows Server 2022 x64 (build 20348)
* using session charset: UTF-8
* checking for file 'mapping/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'mapping' version '1.4'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... [11s] Note_to_CRAN_maintainers
Maintainer: 'Alessio Serafini <srf.alessio@gmail.com>'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'mapping' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking whether startup messages can be suppressed ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [39s] NOTE
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking LazyData ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking examples ... [52s] OK
* checking PDF version of manual ... [14s] OK
* checking HTML version of manual ... OK
* DONE
Status: 1 NOTE

I have the same message if I run the check locally. My version locally installed for sp is 2.0-0

**Comment by rsbivand** [comment]
Please repond to CRAN that the note is expected, not caused by your package, and will cease when the retiring packages are archived and the next `sp` without on load messages is on CRAN in October.

**Comment by serafinialessio** [comment]
Perfect, thank you. I will try

**Comment by serafinialessio** [comment]
> Please repond to CRAN that the note is expected, not caused by your package, and will cease when the retiring packages are archived and the next `sp` without on load messages is on CRAN in October.

CRAN removed my package. How can I remove the statrup message of sp?

**Comment by rsbivand** [comment]
There is by default no startup message with sp 2.1-0 published on CRAN today. Check locally after updating sp and, if the issue is really resolved, resubmit.

**Comment by serafinialessio** [comment]
> There is by default no startup message with sp 2.1-0 published on CRAN today. Check locally after updating sp and, if the issue is really resolved, resubmit.

This is on my local machine with sp 2.1-0

library(sp)
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, were retired in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.

**Comment by rsbivand** [comment]
Please use `Sys.setenv("_SP_STARTUP_MESSAGE_"="none")` or `options("sp_startup_message"="none")` before loading `sp`. @edzer, maybe `sp` 2.1-1 in about  two weeks?

**Comment by serafinialessio** [comment]
> Please use `Sys.setenv("_SP_STARTUP_MESSAGE_"="none")` or `options("sp_startup_message"="none")` before loading `sp`. @edzer, maybe `sp` 2.1-1 in about  two weeks?

Thank you. In the meantime, may I add this in my package and submit it again?

**Comment by rsbivand** [comment]
Yes. Try putting the version you choose in `R/zzz.R` in `onLoad()` - untried. The idea is to set the environment variable or option before the package loads other packages it imports.

**Comment by serafinialessio** [comment]
> Yes. Try putting the version you choose in `R/zzz.R` in `onLoad()` - untried. The idea is to set the environment variable or option before the package loads other packages it imports.


Perfect. Thank you a lot.
